name: App testing

on:
  push:
    branches: [ "master" , "development"]
  pull_request:
    branches: [ "master"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Install pytest
      run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          pytest --cov ./tests/docx/
    - name: Run tests and upload coverage report
      uses: codecov/codecov-action@v3.1.3
